### ISSUE TITLE
call of Dut Black ops zumbi 

### ISSUE THREAD

**Issue by Madaralorde** [Rinnegatamante/Android2Vita-Candidate-Ports-List#375] opened 2023-03-24 03:36 UTC
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity Games

- [X] This game is not made in Unity and does not contain a libunity.so

### No Java Games

- [X] This game is not made in Java and does not contain a libgdx.so

### Game Name

call of duty zombies

### Game Version

1.0.1

### ARM Build Version

ARMv6

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Delisted

**Comment by SofyUchiha** [comment] 2023-03-24 04:50
Duplicate of #50

**Closed** 2023-03-24 09:37 UTC
Labels: Submission
