### ISSUE TITLE
Dead Cells

### ISSUE THREAD

**Issue by jonhv20192231** [Rinnegatamante/Android2Vita-Candidate-Ports-List#374] opened 2023-03-24 02:51 UTC
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity Games

- [X] This game is not made in Unity and does not contain a libunity.so

### No Java Games

- [X] This game is not made in Java and does not contain a libgdx.so

### Game Name

Dead Cells

### Game Version

3.2.4

### ARM Build Version

ARMv7

### OpenGL Version

GLES 1

### FMOD Usage

No FMOD

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=com.playdigious.deadcells.mobile&hl=pt_BR&gl=US

### Comment Box

First I want to thank you for the opportunity you gave the community to choose which game to port to the dear Vita. I believe that a port of Dead Cells would be great for the Vita, as it is a roguelike metroidvania game, a genre that would add to the Vita library that has few good or interesting games like it.

**Comment by SofyUchiha** [comment] 2023-03-24 04:53
Duplicate of #44

**Comment by DeadBossKillOF** [comment] 2023-03-24 07:10
<3

**Closed** 2023-03-24 09:37 UTC
Labels: Submission
